version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    networks:
      - knowhy-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - COMPOSE_HTTP_TIMEOUT=180
      - NODE_OPTIONS="--max-old-space-size=4096"
      - REACT_APP_API_URL=http://3.90.113.180:8000/api
    networks:
      - knowhy-network

networks:
  knowhy-network:
    driver: bridge 